version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6

    steps:

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - run: export PATH=$HOME/.yarn/bin:$PATH

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test